-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM TIME
    WHERE HOUR < 23
)

SELECT TIME.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIME LEFT JOIN ANIMAL_OUTS AO ON TIME.HOUR = HOUR(AO.DATETIME)
GROUP BY TIME.HOUR
ORDER BY TIME.HOUR;