SELECT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소, CONCAT("010-", SUBSTR(TLNO, 4, 4), "-", SUBSTR(TLNO, -4)) AS 전화번호
FROM USED_GOODS_BOARD JOIN USED_GOODS_USER ON WRITER_ID = USER_ID
GROUP BY USER_ID HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC;