SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
, ROUND(AVG(REVIEW_SCORE), 2)
FROM REST_INFO JOIN REST_REVIEW USING(REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY AVG(REVIEW_SCORE) DESC, FAVORITES DESC;