WITH TIME AS (
    SELECT ROWNUM-1 HOUR
    FROM DUAL
    CONNECT BY ROWNUM <= 24
)

SELECT HOUR, COUNT(ANIMAL_ID)
FROM TIME LEFT JOIN ANIMAL_OUTS ON HOUR = TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
GROUP BY HOUR
ORDER BY HOUR