SELECT PRODUCT_ID, PRODUCT_NAME, PRICE*SUM(AMOUNT) AS PRICE
FROM FOOD_ORDER JOIN FOOD_PRODUCT USING(PRODUCT_ID)
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_ID
ORDER BY PRICE DESC, PRODUCT_ID ASC;