-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P JOIN APPOINTMENT A USING(PT_NO) JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N' AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD